import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";

// ✅ ใช้ className แทน variable
const notoSansThai = Noto_Sans_Thai({
  subsets: ["latin"],
  weight: ["400", "700"], // เพิ่มน้ำหนักถ้าต้องการ
  display: "swap",         // เพิ่มเพื่อ performance
});

export const metadata: Metadata = {
  title: "Saving System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansThai.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}